package video_steganography;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Valdez
 */
public class Main extends javax.swing.JFrame {

    private Steganography steg = new Steganography();

    private File coverFile, embedFile, secretFile, File1, File2;

    /**
     * Creates new form main
     */
    public Main() {
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    private void warning(String message) {
        JOptionPane.showMessageDialog(this, message, "Warning", JOptionPane.ERROR_MESSAGE);
    }

    private void info(String message) {
        JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.PLAIN_MESSAGE);
    }

    private String sha1(byte[] input) throws NoSuchAlgorithmException {
        MessageDigest mDigest = MessageDigest.getInstance("SHA1");
        byte[] result = mDigest.digest(input);
        return new BigInteger(1, result).toString(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        File_Chooser = new javax.swing.JFileChooser();
        Title_label = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        Hide_message = new javax.swing.JPanel();
        Secret_message = new javax.swing.JPanel();
        secret_message_area = new javax.swing.JScrollPane();
        secret_message_value = new javax.swing.JTextArea();
        Cover_File1 = new javax.swing.JPanel();
        cover_file_value1 = new javax.swing.JTextField();
        browse_cover_button1 = new javax.swing.JToggleButton();
        hide_button1 = new javax.swing.JToggleButton();
        clear_hide_button1 = new javax.swing.JToggleButton();
        Retrieve_message = new javax.swing.JPanel();
        Embed_File1 = new javax.swing.JPanel();
        embed_file_value1 = new javax.swing.JTextField();
        browse_embed_button1 = new javax.swing.JToggleButton();
        reveal_button1 = new javax.swing.JToggleButton();
        clear_reveal_button1 = new javax.swing.JToggleButton();
        Hide_file = new javax.swing.JPanel();
        Secret_File = new javax.swing.JPanel();
        secret_file_value = new javax.swing.JTextField();
        browse_secret_file_button = new javax.swing.JToggleButton();
        Cover_File2 = new javax.swing.JPanel();
        cover_file_value2 = new javax.swing.JTextField();
        browse_cover_button2 = new javax.swing.JToggleButton();
        hide_button2 = new javax.swing.JToggleButton();
        clear_hide_button2 = new javax.swing.JToggleButton();
        Retrieve_file = new javax.swing.JPanel();
        Embed_File2 = new javax.swing.JPanel();
        embed_file_value2 = new javax.swing.JTextField();
        browse_embed_button2 = new javax.swing.JToggleButton();
        reveal_button2 = new javax.swing.JToggleButton();
        clear_reveal_button2 = new javax.swing.JToggleButton();
        Steganalysis = new javax.swing.JPanel();
        File_1 = new javax.swing.JPanel();
        file_1_value = new javax.swing.JTextField();
        browse_file_1_button = new javax.swing.JToggleButton();
        File_2 = new javax.swing.JPanel();
        file_2_value = new javax.swing.JTextField();
        browse_file_2_button = new javax.swing.JToggleButton();
        Compare = new javax.swing.JPanel();
        compare_hash_button = new javax.swing.JToggleButton();
        compare_chart_button = new javax.swing.JToggleButton();
        compare_byte_button = new javax.swing.JToggleButton();
        from_label = new javax.swing.JLabel();
        from_value = new javax.swing.JTextField();
        to_label = new javax.swing.JLabel();
        to_value = new javax.swing.JTextField();
        About = new javax.swing.JPanel();
        About_label = new javax.swing.JLabel();

        File_Chooser.setCurrentDirectory(new java.io.File("C:\\Users\\tuanp\\OneDrive\\Documents\\NetBeansProjects\\Video Steganography"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Steganography");
        setName("Video Steganography"); // NOI18N
        setResizable(false);

        Title_label.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        Title_label.setForeground(new java.awt.Color(204, 102, 255));
        Title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_label.setText("Video Steganography D14");

        TabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabbedPane.setToolTipText("");
        TabbedPane.setFocusable(false);
        TabbedPane.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N

        Secret_message.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Secret message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 20), new java.awt.Color(0, 0, 255))); // NOI18N

        secret_message_value.setColumns(20);
        secret_message_value.setLineWrap(true);
        secret_message_value.setRows(5);
        secret_message_area.setViewportView(secret_message_value);

        javax.swing.GroupLayout Secret_messageLayout = new javax.swing.GroupLayout(Secret_message);
        Secret_message.setLayout(Secret_messageLayout);
        Secret_messageLayout.setHorizontalGroup(
            Secret_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Secret_messageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secret_message_area)
                .addContainerGap())
        );
        Secret_messageLayout.setVerticalGroup(
            Secret_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Secret_messageLayout.createSequentialGroup()
                .addComponent(secret_message_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        Cover_File1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cover file", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 20), new java.awt.Color(0, 0, 255))); // NOI18N

        browse_cover_button1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        browse_cover_button1.setText("Browse");
        browse_cover_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_cover_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cover_File1Layout = new javax.swing.GroupLayout(Cover_File1);
        Cover_File1.setLayout(Cover_File1Layout);
        Cover_File1Layout.setHorizontalGroup(
            Cover_File1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cover_File1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cover_file_value1)
                .addGap(18, 18, 18)
                .addComponent(browse_cover_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Cover_File1Layout.setVerticalGroup(
            Cover_File1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cover_File1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cover_File1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cover_file_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse_cover_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hide_button1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        hide_button1.setText("Hide");
        hide_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hide_button1ActionPerformed(evt);
            }
        });

        clear_hide_button1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        clear_hide_button1.setText("Clear");
        clear_hide_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_hide_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Hide_messageLayout = new javax.swing.GroupLayout(Hide_message);
        Hide_message.setLayout(Hide_messageLayout);
        Hide_messageLayout.setHorizontalGroup(
            Hide_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hide_messageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hide_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Secret_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cover_File1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(Hide_messageLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(hide_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(clear_hide_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        Hide_messageLayout.setVerticalGroup(
            Hide_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hide_messageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Secret_message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cover_File1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Hide_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hide_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear_hide_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        TabbedPane.addTab("Hide message", Hide_message);

        Embed_File1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Embed file", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 20), new java.awt.Color(0, 0, 255))); // NOI18N

        browse_embed_button1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        browse_embed_button1.setText("Browse");
        browse_embed_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_embed_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Embed_File1Layout = new javax.swing.GroupLayout(Embed_File1);
        Embed_File1.setLayout(Embed_File1Layout);
        Embed_File1Layout.setHorizontalGroup(
            Embed_File1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Embed_File1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(embed_file_value1)
                .addGap(18, 18, 18)
                .addComponent(browse_embed_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Embed_File1Layout.setVerticalGroup(
            Embed_File1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Embed_File1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Embed_File1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(embed_file_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse_embed_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reveal_button1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        reveal_button1.setText("Reveal");
        reveal_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reveal_button1ActionPerformed(evt);
            }
        });

        clear_reveal_button1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        clear_reveal_button1.setText("Clear");
        clear_reveal_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_reveal_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Retrieve_messageLayout = new javax.swing.GroupLayout(Retrieve_message);
        Retrieve_message.setLayout(Retrieve_messageLayout);
        Retrieve_messageLayout.setHorizontalGroup(
            Retrieve_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Retrieve_messageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Embed_File1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Retrieve_messageLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(reveal_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(clear_reveal_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        Retrieve_messageLayout.setVerticalGroup(
            Retrieve_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Retrieve_messageLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Embed_File1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Retrieve_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reveal_button1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(clear_reveal_button1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );

        TabbedPane.addTab("Retrieve message", Retrieve_message);

        Secret_File.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Secret file", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 20), new java.awt.Color(0, 0, 255))); // NOI18N

        browse_secret_file_button.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        browse_secret_file_button.setText("Browse");
        browse_secret_file_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_secret_file_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Secret_FileLayout = new javax.swing.GroupLayout(Secret_File);
        Secret_File.setLayout(Secret_FileLayout);
        Secret_FileLayout.setHorizontalGroup(
            Secret_FileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Secret_FileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secret_file_value)
                .addGap(18, 18, 18)
                .addComponent(browse_secret_file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Secret_FileLayout.setVerticalGroup(
            Secret_FileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Secret_FileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Secret_FileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secret_file_value, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse_secret_file_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cover_File2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cover file", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 20), new java.awt.Color(0, 0, 255))); // NOI18N

        browse_cover_button2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        browse_cover_button2.setText("Browse");
        browse_cover_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_cover_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cover_File2Layout = new javax.swing.GroupLayout(Cover_File2);
        Cover_File2.setLayout(Cover_File2Layout);
        Cover_File2Layout.setHorizontalGroup(
            Cover_File2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cover_File2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cover_file_value2)
                .addGap(18, 18, 18)
                .addComponent(browse_cover_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Cover_File2Layout.setVerticalGroup(
            Cover_File2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cover_File2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cover_File2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cover_file_value2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse_cover_button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hide_button2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        hide_button2.setText("Hide");
        hide_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hide_button2ActionPerformed(evt);
            }
        });

        clear_hide_button2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        clear_hide_button2.setText("Clear");
        clear_hide_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_hide_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Hide_fileLayout = new javax.swing.GroupLayout(Hide_file);
        Hide_file.setLayout(Hide_fileLayout);
        Hide_fileLayout.setHorizontalGroup(
            Hide_fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hide_fileLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(hide_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(clear_hide_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(Hide_fileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hide_fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Secret_File, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cover_File2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Hide_fileLayout.setVerticalGroup(
            Hide_fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hide_fileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Secret_File, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Cover_File2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(Hide_fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hide_button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear_hide_button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        TabbedPane.addTab("Hide file", Hide_file);

        Embed_File2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Embed file", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 20), new java.awt.Color(0, 0, 255))); // NOI18N

        browse_embed_button2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        browse_embed_button2.setText("Browse");
        browse_embed_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_embed_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Embed_File2Layout = new javax.swing.GroupLayout(Embed_File2);
        Embed_File2.setLayout(Embed_File2Layout);
        Embed_File2Layout.setHorizontalGroup(
            Embed_File2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Embed_File2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(embed_file_value2)
                .addGap(18, 18, 18)
                .addComponent(browse_embed_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Embed_File2Layout.setVerticalGroup(
            Embed_File2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Embed_File2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Embed_File2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(embed_file_value2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse_embed_button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reveal_button2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        reveal_button2.setText("Reveal");
        reveal_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reveal_button2ActionPerformed(evt);
            }
        });

        clear_reveal_button2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        clear_reveal_button2.setText("Clear");
        clear_reveal_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_reveal_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Retrieve_fileLayout = new javax.swing.GroupLayout(Retrieve_file);
        Retrieve_file.setLayout(Retrieve_fileLayout);
        Retrieve_fileLayout.setHorizontalGroup(
            Retrieve_fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Retrieve_fileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Embed_File2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Retrieve_fileLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(reveal_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(clear_reveal_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        Retrieve_fileLayout.setVerticalGroup(
            Retrieve_fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Retrieve_fileLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Embed_File2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Retrieve_fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reveal_button2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(clear_reveal_button2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );

        TabbedPane.addTab("Retrieve file", Retrieve_file);

        File_1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "File 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 20), new java.awt.Color(0, 0, 255))); // NOI18N

        browse_file_1_button.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        browse_file_1_button.setText("Browse");
        browse_file_1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_file_1_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout File_1Layout = new javax.swing.GroupLayout(File_1);
        File_1.setLayout(File_1Layout);
        File_1Layout.setHorizontalGroup(
            File_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(file_1_value)
                .addGap(18, 18, 18)
                .addComponent(browse_file_1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        File_1Layout.setVerticalGroup(
            File_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(File_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(file_1_value, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse_file_1_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        File_2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "File 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 20), new java.awt.Color(0, 0, 255))); // NOI18N

        browse_file_2_button.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        browse_file_2_button.setText("Browse");
        browse_file_2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_file_2_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout File_2Layout = new javax.swing.GroupLayout(File_2);
        File_2.setLayout(File_2Layout);
        File_2Layout.setHorizontalGroup(
            File_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(file_2_value, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(browse_file_2_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        File_2Layout.setVerticalGroup(
            File_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(File_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(file_2_value, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse_file_2_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        compare_hash_button.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        compare_hash_button.setText("Compare Hash");
        compare_hash_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compare_hash_buttonActionPerformed(evt);
            }
        });

        compare_chart_button.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        compare_chart_button.setText("Compare in Chart");
        compare_chart_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compare_chart_buttonActionPerformed(evt);
            }
        });

        compare_byte_button.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        compare_byte_button.setText("Compare Bytes");
        compare_byte_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compare_byte_buttonActionPerformed(evt);
            }
        });

        from_label.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        from_label.setText("from");

        from_value.setText("0");

        to_label.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        to_label.setText("to");

        to_value.setText("0");

        javax.swing.GroupLayout CompareLayout = new javax.swing.GroupLayout(Compare);
        Compare.setLayout(CompareLayout);
        CompareLayout.setHorizontalGroup(
            CompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompareLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(CompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CompareLayout.createSequentialGroup()
                        .addComponent(compare_byte_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(from_label))
                    .addComponent(compare_hash_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compare_chart_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CompareLayout.createSequentialGroup()
                        .addComponent(from_value, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(to_label)
                        .addGap(18, 18, 18)
                        .addComponent(to_value, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        CompareLayout.setVerticalGroup(
            CompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compare_hash_button)
                    .addComponent(compare_chart_button))
                .addGap(36, 36, 36)
                .addGroup(CompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CompareLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(from_label))
                    .addGroup(CompareLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(from_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CompareLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(to_label))
                    .addGroup(CompareLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(to_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(compare_byte_button))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SteganalysisLayout = new javax.swing.GroupLayout(Steganalysis);
        Steganalysis.setLayout(SteganalysisLayout);
        SteganalysisLayout.setHorizontalGroup(
            SteganalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SteganalysisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SteganalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(File_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Compare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(File_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SteganalysisLayout.setVerticalGroup(
            SteganalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SteganalysisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(File_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(File_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Compare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("Steganalysis", Steganalysis);

        About_label.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        About_label.setText("<html>\n    <center>\n        <h1 style=\"color:blue;\">\n            Bài tập lớn: giấu tin trong video\n        </h1>\n        <p>Học viện Công nghệ Bưu chính viễn thông</p>\n        <p>Khóa D14 - môn: Mật mã học cơ sở - nhóm 02</p>\n    </center>\n    <br/>\n    <hr/>\n    <div style=\"margin-left:15px;\">\n        <br/>\n        <p>Giảng viên: Thầy Đỗ Xuân Chợ</p>\n        <br/>\n            <p>Các thành viên :</p>\n            <p>Nguyễn Khắc Tiến – B14DCAT220</p>\n            <p>Phạm Mạnh Tuấn – B14DCAT157</p>\n            <p>Nguyễn Tiến Quân – B14DCAT234</p>\n    </div>\n</html>");
        About_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(About_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(About_label, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("About", About);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TabbedPane)
                    .addComponent(Title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browse_cover_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_cover_button1ActionPerformed
        int openfiledailog = File_Chooser.showOpenDialog(this);
        coverFile = File_Chooser.getSelectedFile();

        if (openfiledailog == JFileChooser.CANCEL_OPTION) {
            warning("No file selected!");
        } else {
            cover_file_value1.setText(coverFile.getPath());
        }
    }//GEN-LAST:event_browse_cover_button1ActionPerformed

    private void hide_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hide_button1ActionPerformed
        String secretMessage = secret_message_value.getText();
        String coverFilePath = cover_file_value1.getText();
        if (secretMessage.equalsIgnoreCase("")) {
            warning("Forgot your secret message? :)");
        } else if (coverFilePath.equalsIgnoreCase("")) {
            warning("You haven't cho your cover file!");
        } else {
            try {
                byte[] fileContent = Files.readAllBytes(coverFile.toPath());
                fileContent = steg.hideMessage(secretMessage, fileContent);
                steg.writeFile(fileContent, "embed.avi");
                info("Your secret message has been hidden in file embed.avi.");
            } catch (ArrayIndexOutOfBoundsException e) {
                warning("Cover file must be .avi or message is too long!");
            } catch (IOException e) {
                warning("Error file handling!");
            }
        }
    }//GEN-LAST:event_hide_button1ActionPerformed

    private void clear_hide_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_hide_button1ActionPerformed
        secret_message_value.setText("");
        cover_file_value1.setText("");
    }//GEN-LAST:event_clear_hide_button1ActionPerformed

    private void browse_embed_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_embed_button1ActionPerformed
        int openfiledailog = File_Chooser.showOpenDialog(this);
        embedFile = File_Chooser.getSelectedFile();
        if (openfiledailog == JFileChooser.CANCEL_OPTION) {
            warning("No file selected!");
        } else {
            embed_file_value1.setText(embedFile.getPath());
        }
    }//GEN-LAST:event_browse_embed_button1ActionPerformed

    private void reveal_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reveal_button1ActionPerformed
        String embedFilePath = embed_file_value1.getText();
        if (embedFilePath.equalsIgnoreCase("")) {
            warning("You haven't cho your embed file!");
        } else {
            try {
                byte[] fileContent = Files.readAllBytes(embedFile.toPath());
                new MainResult(steg.findMessage(fileContent)).setVisible(true);
            } catch (ArrayIndexOutOfBoundsException e) {
                warning("Embed file must be .avi!");
            } catch (IOException ex) {
                warning("Error file handling!");
            }
        }
    }//GEN-LAST:event_reveal_button1ActionPerformed

    private void clear_reveal_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_reveal_button1ActionPerformed
        embed_file_value1.setText("");
    }//GEN-LAST:event_clear_reveal_button1ActionPerformed

    private void browse_secret_file_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_secret_file_buttonActionPerformed
        int openfiledailog = File_Chooser.showOpenDialog(this);
        secretFile = File_Chooser.getSelectedFile();

        if (openfiledailog == JFileChooser.CANCEL_OPTION) {
            warning("No file selected!");
        } else {
            secret_file_value.setText(secretFile.getPath());
        }
    }//GEN-LAST:event_browse_secret_file_buttonActionPerformed

    private void browse_cover_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_cover_button2ActionPerformed
        int openfiledailog = File_Chooser.showOpenDialog(this);
        coverFile = File_Chooser.getSelectedFile();
        if (openfiledailog == JFileChooser.CANCEL_OPTION) {
            warning("No file selected!");
        } else {
            cover_file_value2.setText(coverFile.getPath());
        }
    }//GEN-LAST:event_browse_cover_button2ActionPerformed

    private void hide_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hide_button2ActionPerformed
        String secretFilePath = secret_file_value.getText();
        String coverFilePath = cover_file_value2.getText();
        if (secretFilePath.equalsIgnoreCase("")) {
            warning("Forgot your secret file? :)");
        } else if (coverFilePath.equalsIgnoreCase("")) {
            warning("You haven't cho your cover file!");
        } else {
            try {
                byte[] fileContent = Files.readAllBytes(coverFile.toPath());
                byte[] fileSecret = Files.readAllBytes(secretFile.toPath());
                fileContent = steg.hideMessage(new String(fileSecret), fileContent);
                steg.writeFile(fileContent, "embed.avi");
                info("Your secret file has been hidden in file embed.avi.");
            } catch (ArrayIndexOutOfBoundsException e) {
                warning("Cover file must be .avi or message is too long!");
            } catch (IOException e) {
                warning("Error file handling!");
            }
        }
    }//GEN-LAST:event_hide_button2ActionPerformed

    private void clear_hide_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_hide_button2ActionPerformed
        secret_file_value.setText("");
        cover_file_value2.setText("");
    }//GEN-LAST:event_clear_hide_button2ActionPerformed

    private void browse_embed_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_embed_button2ActionPerformed
        int openfiledailog = File_Chooser.showOpenDialog(this);
        embedFile = File_Chooser.getSelectedFile();
        if (openfiledailog == JFileChooser.CANCEL_OPTION) {
            warning("No file selected!");
        } else {
            embed_file_value2.setText(embedFile.getPath());
        }
    }//GEN-LAST:event_browse_embed_button2ActionPerformed

    private void reveal_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reveal_button2ActionPerformed
        String embedFilePath = embed_file_value2.getText();
        if (embedFilePath.equalsIgnoreCase("")) {
            warning("You haven't cho your embed file!");
        } else {
            try {
                byte[] fileContent = Files.readAllBytes(embedFile.toPath());
                String fileSecret = steg.findMessage(fileContent);
                steg.writeFile(fileSecret.getBytes(), "result");
                info("Your secret file has been recover in file named result.");
            } catch (ArrayIndexOutOfBoundsException e) {
                warning("Embed file must be .avi!");
            } catch (IOException ex) {
                warning("Error file handling!");
            }
        }
    }//GEN-LAST:event_reveal_button2ActionPerformed

    private void clear_reveal_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_reveal_button2ActionPerformed
        embed_file_value2.setText("");
    }//GEN-LAST:event_clear_reveal_button2ActionPerformed

    private void browse_file_1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_file_1_buttonActionPerformed
        int openfiledailog = File_Chooser.showOpenDialog(this);
        File1 = File_Chooser.getSelectedFile();

        if (openfiledailog == JFileChooser.CANCEL_OPTION) {
            warning("No file selected!");
        } else {
            file_1_value.setText(File1.getPath());
            try {
                byte[] file1 = Files.readAllBytes(File1.toPath());
                to_value.setText(file1.length + "");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_browse_file_1_buttonActionPerformed

    private void browse_file_2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_file_2_buttonActionPerformed
        int openfiledailog = File_Chooser.showOpenDialog(this);
        File2 = File_Chooser.getSelectedFile();
        if (openfiledailog == JFileChooser.CANCEL_OPTION) {
            warning("No file selected!");
        } else {
            file_2_value.setText(File2.getPath());
        }
    }//GEN-LAST:event_browse_file_2_buttonActionPerformed

    private void compare_hash_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compare_hash_buttonActionPerformed
        String File1Path = file_1_value.getText();
        String File2Path = file_2_value.getText();
        if (File1Path.equalsIgnoreCase("")) {
            warning("You haven't cho your first file!");
        } else if (File2Path.equalsIgnoreCase("")) {
            warning("You haven't cho your second file!");
        } else {
            try {
                byte[] file1 = Files.readAllBytes(File1.toPath());
                byte[] file2 = Files.readAllBytes(File2.toPath());
                if (file1.length != file2.length) {
                    warning("Input files have different size!");
                    return;
                }
                String Hash1 = sha1(file1);
                String Hash2 = sha1(file2);
                String result = "";
                if (!Hash1.equalsIgnoreCase(Hash2)) {
                    result = "File 1 hash:\t" + Hash1 + "\nFile 2 hash:\t" + Hash2;
                    new SteganalysisResult(result).setVisible(true);
                } else {
                    info("There are no different in chosen bytes between two input file!");
                }
            } catch (ArrayIndexOutOfBoundsException e) {
                warning("Cover file must be .avi!");
            } catch (IOException e) {
                warning("Error file handling!");
            } catch (NoSuchAlgorithmException ex) {
                warning("Error while put file(s) into hash!");
            }
        }
    }//GEN-LAST:event_compare_hash_buttonActionPerformed

    private void compare_byte_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compare_byte_buttonActionPerformed
        String File1Path = file_1_value.getText();
        String File2Path = file_2_value.getText();
        if (File1Path.equalsIgnoreCase("")) {
            warning("You haven't cho your first file!");
        } else if (File2Path.equalsIgnoreCase("")) {
            warning("You haven't cho your second file!");
        } else if (from_value.getText().equalsIgnoreCase("") || to_value.getText().equalsIgnoreCase("")) {
            warning("Fill in from/to byte field!");
        } else if (!from_value.getText().matches("\\d+") || !to_value.getText().matches("\\d+")) {
            warning("Invalid from/to value!");
        } else {
            try {
                int from = Integer.parseInt(from_value.getText());
                int to = Integer.parseInt(to_value.getText());
                byte[] file1 = Files.readAllBytes(File1.toPath());
                byte[] file2 = Files.readAllBytes(File2.toPath());
                if (file1.length != file2.length) {
                    warning("Input files have different size!");
                    return;
                }
                boolean check = false;
                String result = "";
                for (int i = from; i < to; i++) {
                    String s1 = String.format("%8s", Integer.toBinaryString(file1[i] & 0xFF)).replace(' ', '0');
                    String s2 = String.format("%8s", Integer.toBinaryString(file2[i] & 0xFF)).replace(' ', '0');
                    if (!s1.equalsIgnoreCase(s2)) {
                        result += "Different byte " + i + ":\t" + s1 + "\t" + s2 + "\n";
                        check = true;
                    }
                }
                if (check) {
                    new SteganalysisResult(result).setVisible(true);
                } else {
                    info("There are no different in chosen bytes between two input file!");
                }
            } catch (ArrayIndexOutOfBoundsException e) {
                warning("Cover file must be .avi!");
            } catch (IOException e) {
                warning("Error file handling!");
            }
        }
    }//GEN-LAST:event_compare_byte_buttonActionPerformed

    private void compare_chart_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compare_chart_buttonActionPerformed
        String File1Path = file_1_value.getText();
        String File2Path = file_2_value.getText();
        if (File1Path.equalsIgnoreCase("")) {
            warning("You haven't cho your first file!");
        } else if (File2Path.equalsIgnoreCase("")) {
            warning("You haven't cho your second file!");
        } else {
            try {
                byte[] file1 = Files.readAllBytes(File1.toPath());
                byte[] file2 = Files.readAllBytes(File2.toPath());
                if (file1.length != file2.length) {
                    warning("Input files have different size!");
                    return;
                }
                new Chart(File1, File2);
            } catch (ArrayIndexOutOfBoundsException e) {
                warning("Cover file must be .avi!");
            } catch (IOException e) {
                warning("Error file handling!");
            }
        }
    }//GEN-LAST:event_compare_chart_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JLabel About_label;
    private javax.swing.JPanel Compare;
    private javax.swing.JPanel Cover_File1;
    private javax.swing.JPanel Cover_File2;
    private javax.swing.JPanel Embed_File1;
    private javax.swing.JPanel Embed_File2;
    private javax.swing.JPanel File_1;
    private javax.swing.JPanel File_2;
    private javax.swing.JFileChooser File_Chooser;
    private javax.swing.JPanel Hide_file;
    private javax.swing.JPanel Hide_message;
    private javax.swing.JPanel Retrieve_file;
    private javax.swing.JPanel Retrieve_message;
    private javax.swing.JPanel Secret_File;
    private javax.swing.JPanel Secret_message;
    private javax.swing.JPanel Steganalysis;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel Title_label;
    private javax.swing.JToggleButton browse_cover_button1;
    private javax.swing.JToggleButton browse_cover_button2;
    private javax.swing.JToggleButton browse_embed_button1;
    private javax.swing.JToggleButton browse_embed_button2;
    private javax.swing.JToggleButton browse_file_1_button;
    private javax.swing.JToggleButton browse_file_2_button;
    private javax.swing.JToggleButton browse_secret_file_button;
    private javax.swing.JToggleButton clear_hide_button1;
    private javax.swing.JToggleButton clear_hide_button2;
    private javax.swing.JToggleButton clear_reveal_button1;
    private javax.swing.JToggleButton clear_reveal_button2;
    private javax.swing.JToggleButton compare_byte_button;
    private javax.swing.JToggleButton compare_chart_button;
    private javax.swing.JToggleButton compare_hash_button;
    private javax.swing.JTextField cover_file_value1;
    private javax.swing.JTextField cover_file_value2;
    private javax.swing.JTextField embed_file_value1;
    private javax.swing.JTextField embed_file_value2;
    private javax.swing.JTextField file_1_value;
    private javax.swing.JTextField file_2_value;
    private javax.swing.JLabel from_label;
    private javax.swing.JTextField from_value;
    private javax.swing.JToggleButton hide_button1;
    private javax.swing.JToggleButton hide_button2;
    private javax.swing.JToggleButton reveal_button1;
    private javax.swing.JToggleButton reveal_button2;
    private javax.swing.JTextField secret_file_value;
    private javax.swing.JScrollPane secret_message_area;
    private javax.swing.JTextArea secret_message_value;
    private javax.swing.JLabel to_label;
    private javax.swing.JTextField to_value;
    // End of variables declaration//GEN-END:variables
}
